version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
    volumes:
     - ./db:/docker-entrypoint-initdb.d

  web:
    image: tomcat:latest
    ports:
     - "80:8080"
    volumes:
     - ./tomcat/webapps:/usr/local/tomcat/webapps
    depends_on:
     - db
